### ISSUE TITLE
Can't set MASS_VHOST_TLD to blank

### ISSUE THREAD

**Issue by hoaivan** [devilbox/docker-nginx-mainline#35]
I need to set vhosts with different domain names suffix such as domain**.com**, domain.**net** ... I tried to set MASS_VHOST_TLD to blank, but can't start the container as it said MASS_VHOST_TLD must be set. 

Pls make default MASS_VHOST_TLD as blank instead of .loc

**Comment by cytopia** [comment]
~~I'm afraid, this is not going to work as the bundled DNS server requires a TLD for its zone.~~

**Comment by cytopia** [comment]
Mixed this up with the Devilbox project itself. Need to look into the request here first.
